If 0, then it is human written. If 1, then it is AI-generated.

In [2]:
from dotenv import load_dotenv
import pandas as pd
from datasets import load_dataset
import kagglehub

In [3]:
path = kagglehub.dataset_download("starblasters8/human-vs-llm-text-corpus")
file_path = f"{path}/data.csv"
grinberg_df = pd.read_csv(file_path, encoding = "latin1")
grinberg_df["label"] = [0 if n == "Human" else 1 for n in grinberg_df["source"]]
grinberg_df = grinberg_df.drop(columns = ["prompt_id", "text_length", "word_count"])
print(f"Dimensions: {grinberg_df.shape}")
print("\n")
print(f"Columns: {grinberg_df.columns}")

Downloading to C:\Users\Chris\.cache\kagglehub\datasets\starblasters8\human-vs-llm-text-corpus\2.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 1.92G/1.92G [01:26<00:00, 23.8MB/s]

Extracting files...

Dimensions: (788922, 3)


Columns: Index(['text', 'source', 'label'], dtype='object')

In [4]:
grinberg_df.head()

                                                text    source  label
0  Federal law supersedes state law, and cannabis...  Bloom-7B      1
1  Miles feels restless after working all day. He...  Bloom-7B      1
2  So first of I am danish. That means that I fol...  Bloom-7B      1
3  In this paper we present a novel rule-based ap...  Bloom-7B      1
4  Most social progressives, love democracy, and ...  Bloom-7B      1

In [5]:
gsingh = load_dataset("gsingh1-py/train")
gsingh_df = gsingh["train"].to_pandas()
gsingh_df = pd.melt(gsingh_df, id_vars = "prompt")
gsingh_df["label"] = [0 if n == "Human_story" else 1 for n in gsingh_df["variable"]]
gsingh_df = gsingh_df.drop(columns = ["prompt"])
gsingh_df = gsingh_df.rename(columns = {"variable":"source", "value":"text"})
print(f"Dimensions: {gsingh_df.shape}")
print("\n")
print(f"Columns: {gsingh_df.columns}")

C:\Users\Chris\anaconda3\envs\ml\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Chris\.cache\huggingface\hub\datasets--gsingh1-py--train. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Repo card metadata block was not found. Setting CardData to empty.
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

train.csv:   0%|          | 0.00/161M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7321 [00:00<?, ? examples/s]

Dimensions: (51247, 3)


Columns: Index(['source', 'text', 'label'], dtype='object')

In [6]:
gsingh_df.head(6)

        source                                               text  label
0  Human_story  Comments\nThe U.S. bombings thatended World Wa...      0
1  Human_story  new video loaded:Messages From Quarantine\ntra...      0
2  Human_story  Supported by\nRoberta Karmel, First Woman Name...      0
3  Human_story  Supported by\nContests\nSummer Reading Contest...      0
4  Human_story  The Week on Instagram\n@heislerphoto was one o...      0
5  Human_story  The New York Times\nArtsBeat|‘Fear the Walking...      0

In [7]:
shahxee = load_dataset("shahxeebhassan/human_vs_ai_sentences")
shahxee_df = shahxee["train"].to_pandas()
shahxee_df["source"] = shahxee_df["label"].map({0: "human", 1: "unknown"})
print(f"Dimensions: {shahxee_df.shape}")
print("\n")
print(f"Columns: {shahxee_df.columns}")

README.md: 0.00B [00:00, ?B/s]

C:\Users\Chris\anaconda3\envs\ml\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Chris\.cache\huggingface\hub\datasets--shahxeebhassan--human_vs_ai_sentences. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

complete_dataset.csv:   0%|          | 0.00/12.7M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/105000 [00:00<?, ? examples/s]

Dimensions: (105000, 3)


Columns: Index(['text', 'label', 'source'], dtype='object')

In [8]:
shahxee_df.head(6)

                                                text  label source
0  Another reason why all students should have to...      0  human
1  Also the Electoral College consists of 538 ele...      0  human
2  Many countries have made changes in there town...      0  human
3  I believe the process of choosing a president ...      0  human
4  A thick cloud of carbon dioxide and heats to h...      0  human
5  A summer break can be defined as a time in whi...      0  human

In [9]:
anagnostou_df = pd.read_csv("https://raw.githubusercontent.com/panagiotisanagnostou/AI-GA/refs/heads/main/ai-ga-dataset.csv")
anagnostou_df = anagnostou_df.drop(columns = ["title"])
anagnostou_df = anagnostou_df.rename(columns = {"abstract":"text"})
anagnostou_df["source"] = anagnostou_df["label"].map({0: "human", 1: "GPT-3"})
print(f"Dimensions: {anagnostou_df.shape}")
print("\n")
print(f"Columns: {anagnostou_df.columns}")

Dimensions: (28662, 3)


Columns: Index(['text', 'label', 'source'], dtype='object')

In [10]:
anagnostou_df.head(6)

                                                text  label source
0  OBJECTIVE: This retrospective chart review des...      0  human
1  Inflammatory diseases of the respiratory tract...      0  human
2  Surfactant protein-D (SP-D) participates in th...      0  human
3  Endothelin-1 (ET-1) is a 21 amino acid peptide...      0  human
4  Respiratory syncytial virus (RSV) and pneumoni...      0  human
5  Nidovirus subgenomic mRNAs contain a leader se...      0  human

In [11]:
combined_df = pd.concat([grinberg_df, shahxee_df, anagnostou_df])
combined_df = combined_df.reset_index(drop = True)

In [12]:
combined_df.to_csv("./data/all_prompts.csv")